array_width = 30
chain_width = 64
fn_args_layout = "Compressed"
hard_tabs = true
max_width = 128
newline_style = "Native"
short_array_element_width_threshold = 32
struct_lit_width = 48
use_field_init_shorthand = true
use_small_heuristics = "Max"

# unstable features below!! run with `cargo +nightly fmt` to use them.
unstable_features = true
brace_style = "AlwaysNextLine"
overflow_delimited_expr = true
